name: RunAction

on:
  workflow_dispatch:

jobs:
  TestDefault:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - shell: pwsh
        run: |
          $PSVersionTable
      - uses: bjompen/UpdatePWSHAction@v1.0.1
      - shell: pwsh
        run: |
          $PSVersionTable
  TestPreview:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - shell: pwsh
        run: |
          $PSVersionTable
      - uses: bjompen/UpdatePWSHAction@v1.0.1
        with:
          ReleaseVersion: 'Preview'
      - shell: pwsh
        run: |
          $PSVersionTable
  TestFixed:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - shell: pwsh
        run: |
          $PSVersionTable
      - uses: bjompen/UpdatePWSHAction@v1.0.1
        with:
          FixedVersion: '7.4.0'
      - shell: pwsh
        run: |
          $PSVersionTable
        
  TestFail:
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - shell: pwsh
        run: |
          $PSVersionTable
      - uses: bjompen/UpdatePWSHAction@v1.0.1
        with:
          FixedVersion: '666.666.666'
        
